### ISSUE TITLE
pyimgurapi.exceptions.PyImgurApiUnauthorized: Permission Denied

### ISSUE THREAD

**Issue by ibndiaye** [nautics889/PyImgurApi#1]
Hey, I like this library and what you're doing. 
I do have a problem with making album. This is my code so far and what its supposed to do is loop through a DIR and then upload individual images then create an album with the image hash. The image hash is the string between the link and the file extension right? https://i.imgur.com/z7f3q2C.jpeg -> so here z7f3q2C?
```

from pyimgurapi import ImgurAPI
from pathlib import Path
import os

REFRESH_TOKEN=""
CLIENT_ID=""
CLIENT_SECRET=""

api=ImgurAPI(
    refresh_token=REFRESH_TOKEN,
    client_id=CLIENT_ID,
    client_secret=CLIENT_SECRET,
)
api.auth

pics_dir=Path("pics/")

pics=os.listdir(pics_dir)
# for f in pics_dir.iterdir():
#     if f.is_file():
#         pics.append(f)

for pic in pics:
    filename=f'pics/{pic}'
    with open(filename, 'rb') as f:
        new_image = api.image.upload(
            f,
            filename,
            title="Rep",  # optional
            description="Absolutely new image"  # optional
        )
    image_link=new_image.data.link
    image_link_tuple=os.path.splitext(image_link)
    image_link_stripped=image_link_tuple[0].removeprefix("https://i.imgur.com/")

    image_ids=[]
    image_ids.append(image_link_stripped)
    # image_ids.append(new_image)
    print(image_link)
    print(image_link_stripped)

api.album.create(
    image_ids=image_ids,
    title='test'
)

# api.image.upload(filename='pics/PI23082000345-1.jpeg',)
# pics=list(pics_dir.iterdir())
print(pics)

```
Everything seems to work but i do get an error at the api.album.create(...)
The error:
```
Traceback (most recent call last):
  File "/home/user/Desktop/imgur_uploader/main.py", line 42, in <module>
    api.album.create(
  File "/home/user/.local/lib/python3.11/site-packages/pyimgurapi/endpoints/album.py", line 51, in create
    return self.make_request(
           ^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/pyimgurapi/endpoints/base_endpoint.py", line 66, in make_request
    raise HTTP_CODES_ERRORS_MAP[e.code](e.reason) from None
pyimgurapi.exceptions.PyImgurApiUnauthorized: Permission Denied
```
Sorry for the possible unclean code, this is a new project

**Comment by ibndiaye** [comment]
Theres also another issue, `urllib.error.HTTPError: HTTP Error 429: Too Many Requests` 
How could I bypass this?

**Comment by nautics889** [comment]
Hello, @ibndiaye!

Apologies for the delayed response and thanks for reporting.
___
>The image hash is the string between the link and the file extension right?

You're absolutely right.
___
The problem with `PermissionError` raises because of missing call of the `.auth()` method. On 15th line you should rather make
```python
api.auth()
```
instead of
```python
api.auth
```
This is required for interacting with Imgur's API in order to get `ACCESS_TOKEN`.
___
One more thing: when you parse the image's hash you should rather make:
```python
image_link_stripped = image_link_tuple[0].replace(
        "https://i.imgur.com/", ""
    )
```
instead of
```python
image_link_stripped=image_link_tuple[0].removeprefix("https://i.imgur.com/")
```
___
Please, use the following code below, i updated this according to the points which i've mentioned:
```python
import os
from pathlib import Path

from pyimgurapi import ImgurAPI

REFRESH_TOKEN = "<your_refresh_token>"
CLIENT_ID = "<your_client_id>"
CLIENT_SECRET = "<your_secret>"

api = ImgurAPI(
    refresh_token=REFRESH_TOKEN,
    client_id=CLIENT_ID,
    client_secret=CLIENT_SECRET,
)
api.auth()

pics_dir = Path("pics/")

pics = os.listdir(pics_dir)
# for f in pics_dir.iterdir():
#     if f.is_file():
#         pics.append(f)

image_ids = []
for pic in pics:
    filename = f'pics/{pic}'
    with open(filename, 'rb') as f:
        new_image = api.image.upload(
            f,
            filename,
            title="Rep",  # optional
            description="Absolutely new image"  # optional
        )
    image_link = new_image.data.link
    image_link_tuple = os.path.splitext(image_link)
    image_link_stripped = image_link_tuple[0].replace(
        "https://i.imgur.com/", ""
    )

    image_ids.append(image_link_stripped)
    # image_ids.append(new_image)
    print(image_link)
    print(image_link_stripped)

api.album.create(
    image_ids=image_ids,
    title='test'
)

# api.image.upload(filename='pics/PI23082000345-1.jpeg',)
# pics=list(pics_dir.iterdir())
print(pics)
```
The code worked for me, uploaded all the images from `./pics/` dir and created the album, adding those images.
___

As for `HTTP 429 Too many requests`. [This response](https://datatracker.ietf.org/doc/html/rfc6585#section-4) is supposed to be sent by Imgur when client sends a lot of requests for a short period of time. 
Does this issue occurs every time? If no, i'd advice to not pay attention to that. However if it keeps appear, i would advice you to wrap the callings with try-except and `sleep()`, something like that:
```python
def call_imgur():
    res = api.<put_here_your_request>
    return res

try:
    res = call_imgur()
except urllib.error.HTTPError:
    time.sleep(10)  # sleep for 10 seconds
    res = call_imgur()
```
If you encountered on this when working with the script which you've attached, i'm sure this happens when trying to upload pictures in a loop. So you might have to simply put `time.sleep(1)` (or whatever number of seconds) inside your `for`-loop.
___
Hope this help!

**Comment by ibndiaye** [comment]
Thanks for the thorough explanations, about the hash, when i upload an image it creates a dictionnary right? Couldnt i get the value by doing this?         `image_id=new_image['id']`.
It works but how could i get info about my newly created album, such as link etc?

**Comment by nautics889** [comment]
@ibndiaye 

Looks like you should add `.data` as the top-level attribute of response object. This is just about how Imgur forms responses: `{"data": {"id": "...", "link": "...", ...etc...}}`

Please, try this:
```python
image_id = new_image["data"]["id"]
```
or even
```python
image_id = new_image.data.id
```
It's up to you which to choose. 

If you want to see full list of attributes that the response object has, you can just print the object and then call attributes by their names.

___

Some notes about the response object...

As you can see, the response object is not a dict but rather a dict-like object, providing dot-notation access to attributes also. It is the instance of `DynamicResponseData`. 
Futhermore, let's suppose you have a `DynamicResponseData` object with the structure like this:
```
{
  "data": {
    "foobar": {
      "a": 1,
      "b": 2
    }
  }
}
```
When you call `resp.data.foobar` **it also returns** `DynamicResponseData` object, so it behaves in recursive manner:
```python
>>> print(response.__class__)  # this is DynamicResponseData
<class 'pyimgurapi.utils.DynamicResponseData'>
>>> print(response)
{
  "data": {
    "foobar": {
      "a": 1,
      "b": 2
    }
  }
}
>>> 
>>> foobar = response.data.foobar
>>> print(response.__class__)
<class 'pyimgurapi.utils.DynamicResponseData'>
>>> foobar = response.data.foobar
>>> print(foobar)
{
  "a": 1,
  "b": 2
}
>>> foobar.__class__  # this is also DynamicResponseData
<class 'pyimgurapi.utils.DynamicResponseData'>
```

**Comment by ibndiaye** [comment]
I've tried `image_id = new_image["data"]["id"]` and its works, thanks for that hint. But when trying to get the newly created album link, it fails

**Comment by nautics889** [comment]
@ibndiaye 
>But when trying to get the newly created album link, it fails

Ahh, ok, it looks like Imgur can call that attribute differently for albums... Give me several minutes pls, i'll take a look on docs...

**Comment by ibndiaye** [comment]
Yeah no rush, I appreciate it

**Comment by nautics889** [comment]
@ibndiaye 

I've figured that out :) Well, when you create an album (`api.create_album()`) the Imgur API responses with 201 HTTP code and provide some content, BUT, the content does not contain [album object](https://api.imgur.com/endpoints/account#album) itself.
Instead, it looks like:
```python
print(album.data)
{
  "id": "...",
  "deletehash": "..."
}
```

___

So, please, modify you code making something like this:
```python
create_album_response = api.album.create(
    image_ids=image_ids,
    title='test'
)

new_ablum = api.album.get(create_album_response.data.id)

print(new_album.data.link)
```
Then you'll be able to see the link of the newly created album. This should work.

**Comment by ibndiaye** [comment]
Great, i had already modified the first part of it. Thanks a lot for explaining how this works!

**Comment by ibndiaye** [comment]
when trying it like mentioned above, i get this error:
```
Traceback (most recent call last):
  File "/home/user/Desktop/imgur_uploader/imgurapi.py", line 67, in <module>
    main()
  File "/home/user/Desktop/imgur_uploader/imgurapi.py", line 65, in main
    create_album('test')
  File "/home/user/Desktop/imgur_uploader/imgurapi.py", line 48, in create_album
    new_album=api.album.get(new_album_response.data.id)
              ^^^^^^^^^^^^^
AttributeError: 'Album' object has no attribute 'get'
```
my function:
```
def create_album(title):
    image_ids=upload_pictures()
    new_album_response=api.album.create(
    image_ids=sorted(image_ids),
    title=title,
    )
    new_album=api.album.get(new_album_response.data.id)
    print(new_album.data.link)
```

**Comment by nautics889** [comment]
@ibndiaye 
My fault, sorry:
```python
new_album = api.album.get_album(new_album_response.data.id)
```
or just
```python
new_album = api.album(new_album_response.data.id)
```
(any of the aboves)
